CREATE TABLE IF NOT EXISTS `llx_pressing_article` (
  `rowid` int(11) NOT NULL AUTO_INCREMENT,
  `entity` int(11) NOT NULL DEFAULT 1,
  `reference` varchar(128) NOT NULL,
  `fk_facture` int(11) DEFAULT NULL,
  `description` text,
  `datec` datetime NOT NULL,
  `tms` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `status` tinyint(4) NOT NULL DEFAULT 0,
  `fk_entrepot` int(11) DEFAULT NULL,
  `longueur` decimal(10,2) DEFAULT NULL,
  `largeur` decimal(10,2) DEFAULT NULL,
  `price_unit` decimal(10,2) DEFAULT NULL,
  `qty` int(11) NOT NULL DEFAULT 1,
  `date_livraison_prevue` datetime DEFAULT NULL,
  `date_livraison` datetime DEFAULT NULL,
  `notes` text,
  `fk_user_author` int(11) DEFAULT NULL,
  `fk_user_responsible` int(11) DEFAULT NULL,
  PRIMARY KEY (`rowid`),
  UNIQUE KEY `uk_ref` (`reference`, `entity`),
  KEY `idx_facture` (`fk_facture`),
  KEY `idx_entrepot` (`fk_entrepot`),
  KEY `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
