CREATE TABLE IF NOT EXISTS llx_fiscalmauritanie_declaration (
  rowid integer AUTO_INCREMENT PRIMARY KEY,
  ref varchar(128) NOT NULL,
  entity integer DEFAULT 1 NOT NULL,
  fk_soc integer DEFAULT NULL,
  company_nif varchar(64) DEFAULT NULL,
  tax_type varchar(50) NOT NULL,
  period varchar(20) NOT NULL,
  period_start date DEFAULT NULL,
  period_end date DEFAULT NULL,
  mode_declaration varchar(50) DEFAULT 'real',
  amount_system double(24,8) DEFAULT 0,
  declared_percentage double(24,8) DEFAULT 100,
  declared_amount double(24,8) DEFAULT 0,
  adjustment_amount double(24,8) DEFAULT 0,
  penalty_amount double(24,8) DEFAULT 0,
  total_amount double(24,8) DEFAULT 0,
  currency_code varchar(3) DEFAULT 'MRU',
  status integer DEFAULT 0,
  payment_status integer DEFAULT 0,
  due_date date DEFAULT NULL,
  payment_date date DEFAULT NULL,
  fk_rule integer DEFAULT NULL,
  note_private text,
  note_public text,
  model_pdf varchar(255) DEFAULT NULL,
  last_main_doc varchar(255) DEFAULT NULL,
  date_validation datetime DEFAULT NULL,
  fk_user_valid integer DEFAULT NULL,
  date_creation datetime NOT NULL,
  tms timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  fk_user_creat integer DEFAULT NULL,
  fk_user_modif integer DEFAULT NULL,
  import_key varchar(14) DEFAULT NULL,
  UNIQUE KEY uk_fiscalmauritanie_declaration_ref_entity (ref, entity),
  KEY idx_fiscalmauritanie_declaration_tax_type (tax_type),
  KEY idx_fiscalmauritanie_declaration_period (period),
  KEY idx_fiscalmauritanie_declaration_due_date (due_date),
  KEY idx_fiscalmauritanie_declaration_status (status),
  KEY idx_fiscalmauritanie_declaration_payment_status (payment_status),
  KEY idx_fiscalmauritanie_declaration_fk_soc (fk_soc)
) ENGINE=innodb;
