CREATE TABLE IF NOT EXISTS llx_fiscalmauritanie_rule (
  rowid integer AUTO_INCREMENT PRIMARY KEY,
  entity integer DEFAULT 1 NOT NULL,
  code varchar(50) NOT NULL,
  label varchar(255) NOT NULL,
  tax_type varchar(50) NOT NULL,
  rate double(24,8) DEFAULT 0,
  minimum_amount double(24,8) DEFAULT 0,
  maximum_amount double(24,8) DEFAULT NULL,
  ceiling_amount double(24,8) DEFAULT NULL,
  frequency varchar(20) DEFAULT 'monthly',
  calculation_method varchar(50) DEFAULT 'rate',
  declared_percentage double(24,8) DEFAULT 100,
  due_day integer DEFAULT NULL,
  due_month integer DEFAULT NULL,
  active tinyint DEFAULT 1,
  note text,
  date_start date DEFAULT NULL,
  date_end date DEFAULT NULL,
  date_creation datetime NOT NULL,
  tms timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  fk_user_creat integer DEFAULT NULL,
  fk_user_modif integer DEFAULT NULL,
  import_key varchar(14) DEFAULT NULL,
  UNIQUE KEY uk_fiscalmauritanie_rule_code_entity (code, entity),
  KEY idx_fiscalmauritanie_rule_tax_type (tax_type),
  KEY idx_fiscalmauritanie_rule_active (active)
) ENGINE=innodb;
